<?php
require 'vendor/autoload.php'; // Include Stripe PHP library

\Stripe\Stripe::setApiKey('sk_test_bhSgB9pO0jya9Lj8Xbs7t8Dv'); // Replace with your Stripe Secret Key

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get payment details from the form
    $token = $_POST['stripeToken']; // Generated by Stripe.js
    $email = $_POST['email']; // Customer email
    $amount = $_POST['amount']; // Payment amount in dollars (e.g., $10.00)

    // Convert the amount to cents
    $amountInCents = $amount * 100;

    try {
        // Create a customer
        $customer = \Stripe\Customer::create([
            'email' => $email,
            'source' => $token,
        ]);

        // Charge the customer
        $charge = \Stripe\Charge::create([
            'customer' => $customer->id,
            'amount' => $amountInCents, // Pass the amount in cents
            'currency' => 'usd',
            'description' => 'Workout Purchase',
        ]);

        // Save transaction details in the database after successful payment
        if ($charge->status === 'succeeded') {
            savePurchaseToDatabase($email, $amountInCents, $charge->id);

            echo "Payment successful! Transaction ID: " . $charge->id;
        }
    } catch (\Stripe\Exception\ApiErrorException $e) {
        // Handle payment failure
        echo 'Error: ' . $e->getMessage();
    }
}

function savePurchaseToDatabase($email, $amountInCents, $transactionId)
{
    // Convert cents back to dollars for saving (optional)
    $amountInDollars = $amountInCents / 100;

    // Add your database insertion logic here
    // Example:
    // $db = new PDO('mysql:host=localhost;dbname=mydatabase', 'username', 'password');
    // $stmt = $db->prepare("INSERT INTO workout_purchases (email, amount, transaction_id) VALUES (?, ?, ?)");
    // $stmt->execute([$email, $amountInDollars, $transactionId]);
}
?>
